fix yaml-linter

diff --git a/.circleci/unittest-config.yml b/.circleci/unittest-config.yml
--- a/.circleci/unittest-config.yml
+++ b/.circleci/unittest-config.yml
@@ -89,13 +89,29 @@ commands:
 
             if << parameters.enable_coverage >>; then
               echo "Running tests with coverage..."
-              bazelisk --host_jvm_args=-Xmx8g coverage //engine/... << parameters.extra_bazel_args >> --combined_report=lcov --jobs=32 --ui_event_filters=-info,-debug,-warning --test_output=errors | tee test_result.log; test_status=${PIPESTATUS[0]}
+              bazelisk --host_jvm_args=-Xmx8g coverage //engine/... \
+                  << parameters.extra_bazel_args >> \
+                  --combined_report=lcov \
+                  --jobs=32 \
+                  --ui_event_filters=-info,-debug,-warning \
+                  --test_output=errors | tee test_result.log
+
+              # Capture the exit status of the Bazel command
+              test_status=${PIPESTATUS[0]}
 
               echo "Processing coverage..."
               lcov --remove bazel-out/_coverage/_coverage_report.dat '*.pb.h' '*.pb.cc' -o bazel-out/_coverage/_coverage_report_filtered.dat
             else
               echo "Running tests without coverage..."
-              bazelisk --host_jvm_args=-Xmx8g test //engine/... << parameters.extra_bazel_args >> --jobs=32 --ui_event_filters=-info,-debug,-warning --test_output=errors | tee test_result.log; test_status=${PIPESTATUS[0]}
+              bazelisk --host_jvm_args=-Xmx8g test //engine/... \
+                  << parameters.extra_bazel_args >> \
+                  --jobs=32 \
+                  --ui_event_filters=-info,-debug,-warning \
+                  --test_output=errors | tee test_result.log
+
+              # Capture the exit status of the Bazel command
+              test_status=${PIPESTATUS[0]}
+
             fi
 
             sh ../devtools/rename-junit-xml.sh
