CI: speed cpp test/coverage execution (#640)
- 使用`--jobs=auto`，让 bazel 自行根据 cpu 决定 action 数量，避免额外切换开销
- 使用 shard_count 分片，并行运行耗时 test

没有变更情况下，test/coverage 都可以正常命中缓存，因此以下皆为修改代码未命中缓存情况下：
bazelisk test 提速
应用前
<img width="1468" height="148" alt="image"
src="https://github.com/user-attachments/assets/97dd3eea-2bec-45ad-8191-d08a7d9d866c"
/>
应用后
<img width="1436" height="156" alt="image"
src="https://github.com/user-attachments/assets/9354c24a-e772-4ae0-a4d1-e13924e4e61a"
/>

bazelisk coverage 提速
应用前
<img width="1494" height="334" alt="image"
src="https://github.com/user-attachments/assets/03b81130-bb92-417f-9339-d67e24a00612"
/>
应用后
<img width="1518" height="436" alt="image"
src="https://github.com/user-attachments/assets/19443e52-2421-45c0-88f5-957ffc991095"
/>

diff --git a/.circleci/unittest-config.yml b/.circleci/unittest-config.yml
--- a/.circleci/unittest-config.yml
+++ b/.circleci/unittest-config.yml
@@ -33,14 +33,6 @@ parameters:
 commands:
   setup_cpp_test:
     steps:
-      # - run:
-      #     name: "Checkout devtools"
-      #     command: git clone https://github.com/secretflow/devtools.git ../devtools
-      # - run:
-      #     name: Setup GCS
-      #     command: |
-      #       echo ${gcs_content} > ../gcs.data
-      #       ../devtools/bazel_cache_setup.py --in_file=../gcs.data --out_file=../gcs.json --min_download
       - run:
           name: Setup BuildBuddy Cache
           command: python3 ./bazel_cache_setup.py
@@ -89,13 +81,31 @@ commands:
 
             if << parameters.enable_coverage >>; then
               echo "Running tests with coverage..."
-              bazelisk --host_jvm_args=-Xmx8g coverage //engine/... << parameters.extra_bazel_args >> --combined_report=lcov --jobs=32 --ui_event_filters=-info,-debug,-warning --test_output=errors | tee test_result.log; test_status=${PIPESTATUS[0]}
+              bazelisk --host_jvm_args=-Xmx8g coverage //engine/... \
+                  << parameters.extra_bazel_args >> \
+                  --combined_report=lcov \
+                  --jobs=auto \
+                  --ui_event_filters=-info,-debug,-warning \
+                  --test_output=errors | tee test_result.log
 
-              echo "Processing coverage..."
-              lcov --remove bazel-out/_coverage/_coverage_report.dat '*.pb.h' '*.pb.cc' -o bazel-out/_coverage/_coverage_report_filtered.dat
+              # Capture the exit status of the Bazel command
+              test_status=${PIPESTATUS[0]}
+              if [ ${test_status} -eq 0 ]; then
+                echo "Processing coverage..."
+                lcov --remove bazel-out/_coverage/_coverage_report.dat '*.pb.h' '*.pb.cc' -o bazel-out/_coverage/_coverage_report_filtered.dat
+              else
+                echo "Bazel coverage failed, skipping lcov processing."
+              fi
             else
               echo "Running tests without coverage..."
-              bazelisk --host_jvm_args=-Xmx8g test //engine/... << parameters.extra_bazel_args >> --jobs=32 --ui_event_filters=-info,-debug,-warning --test_output=errors | tee test_result.log; test_status=${PIPESTATUS[0]}
+              bazelisk --host_jvm_args=-Xmx8g test //engine/... \
+                  << parameters.extra_bazel_args >> \
+                  --jobs=auto \
+                  --ui_event_filters=-info,-debug,-warning \
+                  --test_output=errors | tee test_result.log
+
+              # Capture the exit status of the Bazel command
+              test_status=${PIPESTATUS[0]}
             fi
 
             sh ../devtools/rename-junit-xml.sh
